#!/bin/sh
# This script modifies ".config".

# set kernel compression to LZ4
scripts/config --disable CONFIG_HAVE_KERNEL_BZIP2
scripts/config --disable CONFIG_HAVE_KERNEL_GZIP
scripts/config --disable CONFIG_HAVE_KERNEL_LZMA
scripts/config --disable CONFIG_HAVE_KERNEL_LZO
scripts/config --disable CONFIG_HAVE_KERNEL_XZ
scripts/config --disable CONFIG_HAVE_KERNEL_ZSTD
scripts/config --disable CONFIG_KERNEL_BZIP2
scripts/config --disable CONFIG_KERNEL_GZIP
scripts/config --disable CONFIG_KERNEL_LZMA
scripts/config --disable CONFIG_KERNEL_LZO
scripts/config --disable CONFIG_KERNEL_XZ
scripts/config --disable CONFIG_KERNEL_ZSTD
scripts/config --enable CONFIG_KERNEL_LZ4
scripts/config --enable CONFIG_HAVE_KERNEL_LZ4

# disable everything applel
scripts/config --disable CONFIG_APPLE_GMUX
scripts/config --disable CONFIG_APPLE_MFI_FASTCHARGE
scripts/config --disable CONFIG_APPLE_PROPERTIES
scripts/config --disable CONFIG_BACKLIGHT_APPLE
scripts/config --disable CONFIG_DEV_APPLETALK
scripts/config --disable CONFIG_HID_APPLE
scripts/config --disable CONFIG_HID_APPLEIR
scripts/config --disable CONFIG_KEYBOARD_APPLESPI
scripts/config --disable CONFIG_MACINTOSH_DRIVERS
scripts/config --disable CONFIG_MAC_EMUMOUSEBTN
scripts/config --disable CONFIG_MOUSE_APPLETOUCH
scripts/config --disable CONFIG_SENSORS_APPLESMC
scripts/config --disable CONFIG_USB_APPLEDISPLAY

# disable numa
scripts/config --disable CONFIG_AMD_NUMA
scripts/config --disable CONFIG_NUMA
scripts/config --disable CONFIG_X86_64_ACPI_NUMA

# disable everything ayymd
scripts/config --disable CONFIG_AGP_AMD64
scripts/config --disable CONFIG_AMD8111_ETH
scripts/config --disable CONFIG_AMDTEE
scripts/config --disable CONFIG_AMD_IOMMU
scripts/config --disable CONFIG_AMD_IOMMU_V2
scripts/config --disable CONFIG_AMD_MEM_ENCRYPT
scripts/config --disable CONFIG_AMD_NB
scripts/config --disable CONFIG_AMD_NUMA
scripts/config --disable CONFIG_AMD_PHY
scripts/config --disable CONFIG_AMD_XGBE
scripts/config --disable CONFIG_AMD_XGBE_DCB
scripts/config --disable CONFIG_AMD_XGBE_HAVE_ECC
scripts/config --disable CONFIG_CPU_SUP_AMD
scripts/config --disable CONFIG_DRM_AMDGPU
scripts/config --disable CONFIG_DRM_AMDGPU_CIK
scripts/config --disable CONFIG_DRM_AMDGPU_SI
scripts/config --disable CONFIG_DRM_AMDGPU_USERPTR
scripts/config --disable CONFIG_DRM_AMD_ACP
scripts/config --disable CONFIG_DRM_AMD_DC
scripts/config --disable CONFIG_DRM_AMD_DC_DCN
scripts/config --disable CONFIG_DRM_AMD_DC_DCN3_0
scripts/config --disable CONFIG_DRM_AMD_DC_HDCP
scripts/config --disable CONFIG_DRM_AMD_DC_HDCP
scripts/config --disable CONFIG_DRM_AMD_DC_SI
scripts/config --disable CONFIG_DRM_RADEON
scripts/config --disable CONFIG_EDAC_AMD64
scripts/config --disable CONFIG_GPIO_AMD8111
scripts/config --disable CONFIG_GPIO_AMDPT
scripts/config --disable CONFIG_GPIO_AMD_FCH
scripts/config --disable CONFIG_HSA_AMD
scripts/config --disable CONFIG_HW_RANDOM_AMD
scripts/config --disable CONFIG_I2C_AMD756
scripts/config --disable CONFIG_I2C_AMD756_S4882
scripts/config --disable CONFIG_I2C_AMD8111
scripts/config --disable CONFIG_I2C_AMD_MP2
scripts/config --disable CONFIG_KVM_AMD
scripts/config --disable CONFIG_KVM_AMD_SEV
scripts/config --disable CONFIG_MICROCODE_AMD
scripts/config --disable CONFIG_NET_VENDOR_AMD
scripts/config --disable CONFIG_NTB_AMD
scripts/config --disable CONFIG_PATA_AMD
scripts/config --disable CONFIG_PERF_EVENTS_AMD_POWER
scripts/config --disable CONFIG_PINCTRL_AMD
scripts/config --disable CONFIG_SENSORS_AMD_ENERGY
scripts/config --disable CONFIG_SND_SOC_AMD_ACP
scripts/config --disable CONFIG_SND_SOC_AMD_ACP3x
scripts/config --disable CONFIG_SND_SOC_AMD_CZ_DA7219MX98357_MACH
scripts/config --disable CONFIG_SND_SOC_AMD_CZ_RT5645_MACH
scripts/config --disable CONFIG_SND_SOC_AMD_RENOIR
scripts/config --disable CONFIG_SND_SOC_AMD_RENOIR_MACH
scripts/config --disable CONFIG_SND_SOC_AMD_RV_RT5682_MACH
scripts/config --disable CONFIG_SPI_AMD
scripts/config --disable CONFIG_X86_AMD_FREQ_SENSITIVITY
scripts/config --disable CONFIG_X86_AMD_PLATFORM_DEVICE
scripts/config --disable CONFIG_X86_MCE_AMD

# disable nouveau
scripts/config --disable CONFIG_DRM_NOUVEAU
scripts/config --disable CONFIG_DRM_NOUVEAU_BACKLIGHT
scripts/config --disable CONFIG_DRM_NOUVEAU_SVM

# disable nvidia
scripts/config --disable CONFIG_I2C_NVIDIA_GPU
scripts/config --disable CONFIG_NET_VENDOR_NVIDIA
scripts/config --disable CONFIG_TYPEC_NVIDIA_ALTMODE

# disable google stuff
scripts/config --disable CONFIG_GOOGLE_COREBOOT_TABLE
scripts/config --disable CONFIG_GOOGLE_FIRMWARE
scripts/config --disable CONFIG_GOOGLE_FRAMEBUFFER_COREBOOT
scripts/config --disable CONFIG_GOOGLE_MEMCONSOLE
scripts/config --disable CONFIG_GOOGLE_MEMCONSOLE_COREBOOT
scripts/config --disable CONFIG_GOOGLE_VPD
scripts/config --disable CONFIG_NET_VENDOR_GOOGLE
scripts/config --disable CONFIG_HID_GOOGLE_HAMMER

# disable ching chong stuff (huawei & xiaomi)
scripts/config --disable CONFIG_HUAWEI_WMI
scripts/config --disable CONFIG_NET_VENDOR_HUAWEI
scripts/config --disable CONFIG_USB_NET_HUAWEI_CDC_NCM
scripts/config --disable CONFIG_XIAOMI_WMI

# disable other unused stuff (broadcom, fujitsu, centaur,
# hygon, marvell, mediatek, qualcomm, rockchip, sifive, zhaoxin)
scripts/config --disable CONFIG_BROADCOM_PHY
scripts/config --disable CONFIG_CPU_SUP_CENTAUR
scripts/config --disable CONFIG_CPU_SUP_HYGON
scripts/config --disable CONFIG_CPU_SUP_ZHAOXIN
scripts/config --disable CONFIG_FUJITSU_ES
scripts/config --disable CONFIG_FUJITSU_LAPTOP
scripts/config --disable CONFIG_FUJITSU_TABLET
scripts/config --disable CONFIG_MARVELL_10G_PHY
scripts/config --disable CONFIG_MARVELL_PHY
scripts/config --disable CONFIG_NET_VENDOR_BROADCOM
scripts/config --disable CONFIG_NET_VENDOR_FUJITSU
scripts/config --disable CONFIG_NET_VENDOR_MARVELL
scripts/config --disable CONFIG_NET_VENDOR_QUALCOMM
scripts/config --disable CONFIG_PATA_MARVELL
scripts/config --disable CONFIG_QCOM_QMI_HELPERS
scripts/config --disable CONFIG_ROCKCHIP_PHY
scripts/config --disable CONFIG_SPI_ROCKCHIP
scripts/config --disable CONFIG_SPI_SIFIVE
scripts/config --disable CONFIG_USB_SERIAL_QUALCOMM
scripts/config --disable CONFIG_WLAN_VENDOR_BROADCOM
scripts/config --disable CONFIG_WLAN_VENDOR_MARVELL
scripts/config --disable CONFIG_WLAN_VENDOR_MEDIATEK

# disable touchscreens (who uses touchscreens on a pc?)
scripts/config --disable CONFIG_TOUCHSCREEN_FUJITSU

# optimize for performance, not for size
scripts/config --enable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE
scripts/config --disable CONFIG_CC_OPTIMIZE_FOR_SIZE

# set default governor to performance
scripts/config --enable CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE
scripts/config --disable CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL

# disable unused sound modules
scripts/config --disable CONFIG_DVB_BT8XX
scripts/config --disable CONFIG_GPIO_BT8XX
scripts/config --disable CONFIG_SND_ALI5451
scripts/config --disable CONFIG_SND_ALS300
scripts/config --disable CONFIG_SND_ALS4000
scripts/config --disable CONFIG_SND_ASIHPI
scripts/config --disable CONFIG_SND_ATIIXP
scripts/config --disable CONFIG_SND_ATIIXP_MODEM
scripts/config --disable CONFIG_SND_AU8810
scripts/config --disable CONFIG_SND_AU8820
scripts/config --disable CONFIG_SND_AU8830
scripts/config --disable CONFIG_SND_AW2
scripts/config --disable CONFIG_SND_AZT3328
scripts/config --disable CONFIG_SND_BT87X
scripts/config --disable CONFIG_SND_CA0106
scripts/config --disable CONFIG_SND_CMIPCI
scripts/config --disable CONFIG_SND_CS4281
scripts/config --disable CONFIG_SND_CS46XX
scripts/config --disable CONFIG_SND_CS46XX_NEW_DSP
scripts/config --disable CONFIG_SND_CTXFI
scripts/config --disable CONFIG_SND_DARLA20
scripts/config --disable CONFIG_SND_DARLA24
scripts/config --disable CONFIG_SND_ECHO3G
scripts/config --disable CONFIG_SND_EMU10K1
scripts/config --disable CONFIG_SND_EMU10K1X
scripts/config --disable CONFIG_SND_EMU10K1_SEQ
scripts/config --disable CONFIG_SND_ENS1370
scripts/config --disable CONFIG_SND_ENS1371
scripts/config --disable CONFIG_SND_ES1938
scripts/config --disable CONFIG_SND_ES1968
scripts/config --disable CONFIG_SND_ES1968_INPUT
scripts/config --disable CONFIG_SND_ES1968_RADIO
scripts/config --disable CONFIG_SND_FM801
scripts/config --disable CONFIG_SND_FM801_TEA575X_BOOL
scripts/config --disable CONFIG_SND_GINA20
scripts/config --disable CONFIG_SND_GINA24
scripts/config --disable CONFIG_SND_HDSP
scripts/config --disable CONFIG_SND_HDSPM
scripts/config --disable CONFIG_SND_ICE1712
scripts/config --disable CONFIG_SND_ICE1724
scripts/config --disable CONFIG_SND_INDIGO
scripts/config --disable CONFIG_SND_INDIGODJ
scripts/config --disable CONFIG_SND_INDIGODJX
scripts/config --disable CONFIG_SND_INDIGOIO
scripts/config --disable CONFIG_SND_INDIGOIOX
scripts/config --disable CONFIG_SND_KORG1212
scripts/config --disable CONFIG_SND_LAYLA20
scripts/config --disable CONFIG_SND_LAYLA24
scripts/config --disable CONFIG_SND_LOLA
scripts/config --disable CONFIG_SND_LX6464ES
scripts/config --disable CONFIG_SND_MAESTRO3
scripts/config --disable CONFIG_SND_MAESTRO3_INPUT
scripts/config --disable CONFIG_SND_MIA
scripts/config --disable CONFIG_SND_MIXART
scripts/config --disable CONFIG_SND_MONA
scripts/config --disable CONFIG_SND_NM256
scripts/config --disable CONFIG_SND_OXYGEN
scripts/config --disable CONFIG_SND_OXYGEN_LIB
scripts/config --disable CONFIG_SND_PCXHR
scripts/config --disable CONFIG_SND_RIPTIDE
scripts/config --disable CONFIG_SND_RME32
scripts/config --disable CONFIG_SND_RME96
scripts/config --disable CONFIG_SND_RME9652
scripts/config --disable CONFIG_SND_SE6X
scripts/config --disable CONFIG_SND_SONICVIBES
scripts/config --disable CONFIG_SND_TRIDENT
scripts/config --disable CONFIG_SND_VIA82XX
scripts/config --disable CONFIG_SND_VIA82XX_MODEM
scripts/config --disable CONFIG_SND_VIRTUOSO
scripts/config --disable CONFIG_SND_VX222
scripts/config --disable CONFIG_SND_YMFPCI

# set max number of GPUs to 2
scripts/config --set-val CONFIG_VGA_ARB_MAX_GPUS 2

# set max number of CPU cores/threads to 8
scripts/config --set-val CONFIG_NR_CPUS 8
scripts/config --set-val CONFIG_NR_CPUS_DEFAULT 8

# disable FireWire (who uses firewire?)
scripts/config --disable CONFIG_FIREWIRE
scripts/config --disable CONFIG_FIREWIRE_NOSY
